### ISSUE TITLE
Document all function calls

### ISSUE THREAD

**Issue by kevinburke** [rustls/rustls-ffi#130]
I can go to e.g. https://docs.rs/rustls/0.18.1/rustls/ and get an overview of all of the function calls and types in the rustls package. It would be nice if there was a page that documented these for rustls-ffi that was available from the README or Github homepage.

**Comment by sagebind** [comment]
This will probably be done for free once rustls-ffi is published on Crates.io. See also #116.

**Comment by jsha** [comment]
Yes, once rustls-ffi is published on crates.io there will be documentation available on docs.rs. If you want to see that documentation today, you can run `cargo doc --open` locally. Unfortunately, that documentation shows the Rust-style declarations rather than the C-style declarations.

For now, the main documentation of function calls is in rustls.h, which has many comments. This is of course not an ideal format for documentation. I'd like to have a series of pages dedicated to groups of functions, similar to how many pages are laid out - or maybe actually in the man page format.

On the other hand, it's really nice to document things inline with doccomments and use a tool to generate the documentation pages. If rustdoc could generate documentation that shows the C declarations of things, that might be a preferable option; but it would require some work to make it happen.

**Comment by jsha** [comment]
I think this is done.
