### ISSUE TITLE
All PR's currently fail CI

### ISSUE THREAD

**Issue by kevinburke** [rustls/rustls-ffi#139]
It looks like there is a check related to pernos.co that is currently failing all builds, which can obscure the presence of legitimate failures. Could we disable the check, or get it working again?

**Comment by tgeoghegan** [comment]
I have no idea what persnosco is and I can't see anything in `rustls-ffi`'s GitHub actions YAML that would turn it on. Maybe there's something at the `rustls` organization level that's trying to apply it to all child repositories? @djc, does Pernosco ring any bells for you?

**Comment by djc** [comment]
Yeah, I installed the Pernosco GitHub to aid debugging in Rustls, but wasn't aware it would affect all repos in the org. I think the failed status is probably unintentional/a bug. @rocallahan?

**Comment by rocallahan** [comment]
Sorry, I'll fix this ASAP

**Comment by rocallahan** [comment]
Actually, I think you can fix this at your end by installing the app and enabling it just for the `rustls` repository instead of all repositories.

**Comment by rocallahan** [comment]
>  I think the failed status is probably unintentional/a bug.

It was intentional. If someone installs the Pernosco app and tries to use it, but that usage is not authorized by us (yet), then I want to give some feedback so I recently made the change to add a status message to that effect.

I can undo that change to fix your problem, but it probably makes more sense for you to simply restrict the app to `rustls`. For example:

![image](https://user-images.githubusercontent.com/296135/133862185-a50247da-8ff7-4ff8-bdae-50cb35d8f018.png)

**Comment by rocallahan** [comment]
That's accessible via Github's "Settings" ... "Integrations" / "Installed Github Apps".

**Comment by djc** [comment]
Disabled Pernosco for this repository for now, sorry about that.
