### ISSUE TITLE
Windows: write_vectored_cb()

### ISSUE THREAD

**Issue by gvanem** [rustls/rustls-ffi#173]
The vectored callback is not enabled for Winsock. But trying it and trusting the comment in
`src/rustls.h` for `struct rustls_iovec`:
```
/**
 * An alias for `struct iovec` from uio.h (on Unix) or `WSABUF` on Windows. You should cast
 * `const struct rustls_iovec *` to `const struct iovec *` on Unix, or `const *LPWSABUF`
 * on Windows. See [`std::io::IoSlice`] for details on interoperability with platform
 * specific vectored IO.
 */
```
Like:
```c
  if (WSASend(conn->fd, (LPWSABUF)iov, count, &n, 0, NULL, NULL) < 0) {
```

With a `set VECTORED_IO=1`and running the `client.exe` program, it gives me a `WSAEFAULT` from Winsock2
(`Error in rustls_connection_write_tls: errno 10014`)

Reason seems to be one cannot simply cast to a `LPWSABUF`. The layouts differ.
Reading https://docs.w3cub.com/rust/std/io/struct.ioslice did convince me a cast is good.

But this code with a locally defined `struct _iovec` works:
```c
rustls_io_result write_vectored_cb(
    void *userdata, const struct rustls_iovec *iov, size_t count, size_t *out_n)
{
  struct conndata *conn = (struct conndata *)userdata;

#ifdef _WIN32
  struct _iovec {
    void  *iov_base;
    size_t iov_len;
  };
  struct _iovec *_iov = (struct _iovec *) iov;
  DWORD n = 0;
  WSABUF *wsabufs = alloca (count * sizeof(WSABUF));
  int  i;

  for (i = 0; i < count; i++)
  {
    wsabufs[i].len = _iov[i].iov_len;
    wsabufs[i].buf = _iov[i].iov_base;
  }
  if (WSASend(conn->fd, wsabufs, count, &n, 0, NULL, NULL) < 0) {
    return errno;
  }
  *out_n = n;
#else
  ssize_t n = 0;
  n = writev(conn->fd, (const struct iovec *)iov, count);
  if(n < 0) {
    return errno;
  }
  *out_n = n;
#endif
  return 0;
}
```

Can someone please explain this?

**Comment by jsha** [comment]
That is indeed a bit mysterious to me. Note that https://doc.rust-lang.org/std/io/struct.IoSlice.html says:

> It is semantically a wrapper around a &[u8], but is guaranteed to be ABI compatible with the iovec type on Unix platforms and WSABUF on Windows.

That is, it mentions `WSABUF`, not `LPWSABUF`. But [reading the windows docs](https://docs.microsoft.com/en-us/windows/win32/api/ws2def/ns-ws2def-wsabuf), it seems like `LPWSABUF` should be equivalent to `*WSABUF`, which should make it equivalent to `*rustls_iovec`.

An experiment: If you cast iov to `LPWSABUF` as in your first example, but instead of passing to WSASend, just print the `len` field, do you get sensible numbers or garbage?

Also worth noting: `struct iovec` on Unix [is defined with the pointer first, and len second](https://man7.org/linux/man-pages/man2/writev.2.html). On Windows, WSABUF is defined with the len first and pointer second.

The results you're getting seem compatible with the `iov` you receive being structured Unix-style instead of Windows-style, even though Rust guarantees it should be structured Windows-style on Windows. Hmm.

**Comment by jsha** [comment]
I think this is the problem: https://github.com/rustls/rustls-ffi/blob/9c76360d3212db1cc6aa998ebd5490f5ccf3fbde/src/io.rs#L156-L164

We turn each IoSlice into a `rustls_slice_bytes`, which happens to have the same layout as a Unix-style `struct iovec`, but has the fields reversed from a Windows-style WSABUF. We shouldn't be doing that transformation at all, but should pass a pointer to the beginning of the slice directly.

**Comment by jsha** [comment]
It looks like there was actually some discussion of this on the original PR adding vectored write support: https://github.com/rustls/rustls-ffi/pull/112#issuecomment-864320536
