### ISSUE TITLE
Replacement for _config_builder_from_from_config mechanism

### ISSUE THREAD

**Issue by icing** [rustls/rustls-ffi#200]
Looking at the changes in v0.8.0, one sticks out to me:

```
rustls_client_config_builder_from_config and rustls_server_config_builder_from_config have been removed.
```

which means i have to rewrite connection handling on `mod_tls` for dynamic certificates and virtual host SNI selection.

The explanation sounds as if some internal design makes this API use case now impossible. Since the one discussed `ClientHelloReader` did not happen, have you discarded the server use case? Or is there an upcoming v0.8.1 addition which I should wait for?

Thanks for you help.

**Comment by jsha** [comment]
The ClientHelloReader wound up as Acceptor in the rustls API. We have an open ticket here to implement it in rustls: https://github.com/rustls/rustls-ffi/issues/155. For mod_tls you should probably wait for that to be implemented in rustls, since it's needed for your use case. Sorry for not directly reaching out to you about it previously!

**Comment by icing** [comment]
No problem. Without `from_config()` constructors, I need to remodel the code there anyway. (which was a bit of a surprise, since now mod_tls will have no preconfigured `rustls_server_config` any more. Everything will need to be instantiated per connection.)

**Comment by cpu** [comment]
I think this has been addressed. There are now ffi bindings for `rustls_acceptor` and AFAICT `mod_tls` has been adjusted accordingly.
