### ISSUE TITLE
Bindings to `rustls-platform-verifier`?

### ISSUE THREAD

**Issue by amesgen** [rustls/rustls-ffi#417]
Any thoughts on including bindings to [`rustls-platform-verifier`](https://github.com/rustls/rustls-platform-verifier)? AFAICT the reasons listed in https://github.com/rustls/rustls-ffi/pull/110 (which removed `rustls-native-roots`) do not apply to it.

E.g. sth like this (maybe also taking in additional root certs):
```rust
#[no_mangle]
pub extern "C" fn rustls_platform_verifier_server_cert_verifier(
    verifier_out: *mut *mut rustls_server_cert_verifier,
) -> rustls_result {
    ffi_panic_boundary! {
        let verifier_out = try_mut_from_ptr_ptr!(verifier_out);
        let verifier = Arc::new(rustls_platform_verifier::Verifier::new());
        set_boxed_mut_ptr(verifier_out, verifier);
        rustls_result::Ok
    }
}
```

However, it still might be considered out-of-scope for this project, or it might be too new of a project to include here.

**Comment by cpu** [comment]
:wave: thanks for opening the issue.

From my perspective I think it makes sense to offer as an optional feature. The platform verifier crate is young, but now that it's published in crates.io, is gradually being adopted in other crates (e.g. [hyper-rustls](https://github.com/rustls/hyper-rustls/pull/253) and [quinn](https://github.com/quinn-rs/quinn/pull/1734)).

I think it would be helpful to hear what @jsha thinks since the work would require his review to be merged.

**Comment by jsha** [comment]
I think bindings to rustls-platform-verifier would be awesome! That's the
direction we want the ecosystem to move in, so we should get it set up in
the FFI bindings early.
